spring.main.web-application-type=none
spring.main.banner-mode=off
spring.ai.mcp.server.stdio=true
spring.ai.mcp.server.name=selenium-mcp-java
spring.ai.mcp.server.version=0.0.1

logging.pattern.console=
logging.file.name=mcp-server.log
